export {default as LoginPage} from './auth/loginPage/loginPage'
export {default as MainPage} from './workspace/MainPage/MainPage'
export {default as RegistrationPage} from './auth/registrationPage/RegistrationPage'
export {default as Service} from './workspace/Service/Service'
export {default as Home} from './public/home/home'
export {default as ProductCatalog} from './workspace/ProductCatalog/ProductCatalog'
export {default as Cashbox} from './workspace/Cashbox/Cashbox'
