export interface Service {
    id: number,
    createdAt: string,
    updatedAt: string,
    enabled: boolean,
    name: string,
    status: string,
    clientId: string,
    clientDescription: string,
    userCreatedId: string,
    userUpdatedId: string,
    userCreatedDescription: string,
    userMasterId: string,
    userMasterDescription: string,
    userDeletedId: string,
    workDiscountId: number,
    productDiscountId: number,
    priceWork: number,
    discountWork: number,
    totalWork: number,
    priceProduct: number,
    discountProduct: number,
    totalProduct: number,
    price: number,
    discount: number,
    total: number,
    shopId: number
}