export {HeaderUserMenu} from './HeaderUserMenu/HeaderUserMenu'
export {HeaderShopMenu} from './HeaderShopMenu/HeaderShopMenu'

export {ServiceArchiveModal} from './ArchiveModals/ServiceArchiveModal/ServiceArchiveModal'
export {ServiceFinalArchiveModal} from './ArchiveModals/ServiceFinalArchiveModal/ServiceFinalArchiveModal'
export {InventoryOfProductsArchiveModal} from './ArchiveModals/InventoryOfProductsArchiveModal/InventoryOfProductsArchiveModal'
export {SupplyInvoiceArchiveModal} from './ArchiveModals/SupplyInvoiceArchiveModal/SupplyInvoiceArchiveModal'
export {EncashmentArchiveModal} from './ArchiveModals/EncashmentArchiveModal/EncashmentArchiveModal'
export {CheckArchiveModal} from './ArchiveModals/CheckArchiveModal/CheckArchiveModal'
export {StorageProductsTransferArchiveModal} from './ArchiveModals/StorageProductsTransferArchiveModal/StorageProductsTransferArchiveModal'

export {ConfirmModal} from './ConfirmModal/ConfirmModal'
export {PrintModal} from './PrintModal/PrintModal'
export {UserRoleModal} from './UserRoleModal/UserRoleModal'
export {CreateRoleGroupModal} from './UserRoleModal/CreateRoleGroupModal'

export {PayModal} from './PayModal/PayModal'
export {ChooseClientModal} from './ChooseClientModal/ChooseClientModal'
export {ChooseDiscountModal} from './ChooseDiscountModal/ChooseDiscountModal'

export {EmployeeSalaryModal} from './EmployeeSalaryModal/EmployeeSalaryModal'
export {EndWorkDayModal} from './EndWorkDayModal/EndWorkDayModal'
export {ReportDayModal} from './ReportDayModal/ReportDayModal'
export {EncashmentModal} from './CashboxModals/EncashmentModal/EncashmentModal'
export {GetPutMoneyModal} from './CashboxModals/GetPutMoneyModal/GetPutMoneyModal'

export {EditProductCardModal} from './ProductCatalogFeatures/EditProductCardModal/EditProductCardModal'
export {UpdateProductPricesModal} from './ProductCatalogFeatures/UpdateProductPricesModal/UpdateProductPricesModal'
export {CreateProductModal} from './ProductCatalogFeatures/CreateProductModal/CreateProductModal'
export {ChooseProductModal} from './ProductCatalogFeatures/ChooseProductModal/ChooseProductModal'
export {UpdateProductModal} from './ProductCatalogFeatures/UpdateProductModal/UpdateProductModal'
export {CreateTagModal} from './ProductCatalogFeatures/CreateTagModal/CreateTagModal'
export {ChooseProductTagModal} from './ProductCatalogFeatures/ChooseProductTagModal/ChooseProductTagModal'
export {UpdateTagModal} from './ProductCatalogFeatures/UpdateTagModal/UpdateTagModal'

export {SelectProductModal} from './ServiceFeatures/SelectProductWorkModals/SelectProductModal'
export {SelectWorkModal} from './ServiceFeatures/SelectProductWorkModals/SelectWorkModal'
export {TableProductItem} from './ServiceFeatures/TableProductItem/TableProductItem'
export {TableProductItemAdditional} from './ServiceFeatures/TableProductItem/TableProductItemAdditional'
export {CreateWorkGroupModal} from './WorkCatalogFeatures/CreateWorkGroupModal/CreateWorkGroupModal'
export {CreateWorkModal} from './WorkCatalogFeatures/CreateWorkModal/CreateWorkModal'
export {UpdateWorkGroupModal} from './WorkCatalogFeatures/UpdateWorkGroupModal/UpdateWorkGroupModal'
export {UpdateWorkModal} from './WorkCatalogFeatures/UpdateWorkModal/UpdateWorkModal'

export {CreateShopModal} from './CRUDModals/CreateShopModal/CreateShopModal'
export {CreateStorageModal} from './CRUDModals/CreateStorageModal/CreateStorageModal'
export {CreateCurrencyModal} from './CRUDModals/CreateCurrencyModal/CreateCurrencyModal'
export {CreateQuantityUnitModal} from './CRUDModals/CreateQuantityUnitModal/CreateQuantityUnitModal'
export {CreateSpecificationModal} from './CRUDModals/CreateSpecificationModal/CreateSpecificationModal'
export {CreateOptionModal} from './CRUDModals/CreateOptionModal/CreateOptionModal'


