version: '3'
services:
  bikeshop.frontend:
    container_name: bikeshop-frontend
    image: nomadrilius/bikeshop.frontend
    hostname: bikeshop.frontend
    ports: 
      - 3000:80
    restart: on-failure

    links:
      - bikeshop.frontend
    depends_on:
      - bikeshop.frontend
