import React from 'react';
import parse from "html-react-parser";

const DeliveryPayment = () => {
    return (
        <div>
            {parse("<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\"><strong><ins>Доставка товару</ins></strong></span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Ми робимо все можливе, щоб Ви отримали замовлення якнайшвидше. </span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Після того, як Ви оформите замовлення, розпочнеться його опрацювання - наш консультант сконтактує з Вами у месенджерах, щоб уточнити перелік товарів, їх наявність та ін. деталі. Опрацювання та відправлення замовлень відбувається в робочі дні. Опрацювання замовлень, оформлених в суботу та неділю, а також в святкові вихідні відбувається на наступний робочий день**. </span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Для доставки своїх товарів ми використовуємо послуги зовнішніх кур’єрських компаній: на даний момент, вся доставка замовлень з нашого магазину здійснюється лише до відділень / поштоматів Нової Пошти. </span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Зберігання посилки у відділенні Нової Пошти відбуватиметься за правилами перевізника, а після закінчення стандартного безкоштовного терміну зберігання замовлення, яке не було отримане Покупцем, буде повернуто Продавцю.</span>&nbsp;</p>\n" +
                "<p style=\"text-align:left;\"><br><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\"><ins>Повернення товару</ins></span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Ви маєте право на повернення товару, який не використовувася, протягом 14 днів з моменту його доставки. Якщо Ви не повернули товар протягом цього терміну, а також, якщо товар був у використанні – повернення не зможе бути оформленим. Товар повинен повертатись разом із своєю оригінальною упаковкою. Якщо товар, який Ви хочете повернути продавався як набір / комплект із декількох товарів, повернення буде оформлене лише в випадку повернення всього комплекту / набору.</span> <span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\"><ins>Перелік товарів, які не підлягають поверненню визначено Законом “Про захист прав споживачів”</ins>.</span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Якщо товар, що підлягає поверненню, Вам не підійшов, напишіть нам в меседжер (viber / whatsapp, telegram) і ми оформимо повернення. </span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\"><ins>Після оформлення</ins>, товар, що не підійшов, потрібно надіслати нам - ми надамо дані (№ відділення Нової пошти) для доставки.</span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Відправлення товару, що не підійшов, відбувається за рахунок Покупця. Для оформлення повернення коштів за товар, що не підійшов, необхідно заповинити Заяву на повернення (буде надана). Разом із Заявою, Ви повинні докласти у посилку фіскальний чек (що був надісланий Вам після оплати) або видаткову накладну (була вкладена Вам у посилку, якщо оплата замовлення відбувалась при отриманні). Повернення коштів за товар, що не підійшов, відбуватиметься безготівково****. Повернення коштів відбудеться протягом 7 робочих днів після отримання (та перевірки) товару.</span></p>\n" +
                "<p style=\"text-align:left;\"><span style=\"color: rgb(134,116,105);font-size: 13px;font-family: Tahoma, Geneva, sans-serif;\">Будь-які зміни до умов та правил доставки, оплати та повернення товару можуть бути змінені та набувають чинності в момент їх публікації на цьому веб-сайті. Переглядайте цей розділ час від часу.</span>&nbsp;</p>\n" +
                "<p style=\"text-align:start;\"><span style=\"color: rgb(51,51,51);background-color: rgb(255,255,255);font-size: 13px;font-family: Open Sans\", Roboto;\">Оплата:</span></p>\n" +
                "<p style=\"text-align:start;\"><span style=\"color: rgb(51,51,51);background-color: rgb(255,255,255);font-size: 13px;font-family: Open Sans\", Roboto;\">- післяплатою (оплата проводиться в момент отримання товару).</span></p>\n" +
                "<p style=\"text-align:start;\"><span style=\"color: rgb(51,51,51);background-color: rgb(255,255,255);font-size: 13px;font-family: Open Sans\", Roboto;\">- Онлайн оплата- (онлайн-оплата Liqpay) - найвигідніший і зручний спосіб. Для того, щоб оплатити товар дистанційно, при оформленні замовлення виберіть пункт «Онлайн-оплата». Після підтвердження замовлення нашим менеджером протягом години, вас перенаправить на сторінку сервісу, де ви зможете вибрати один з варіантів внесення коштів.</span></p>\n")}
        </div>
    );
};

export default DeliveryPayment;